version: 2
updates:
  # Check for updates of crates and actions every month.  We don't check for
  # Rust updates because it's a nuisance to get so many pull requests, and we
  # can just cargo update once in a while.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    assignees: [swsnr]
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: monthly
    assignees: [swsnr]
    # Ignore minor and patch updates; downstream consumers
    # can do these; we only need to check for semver
    # incompatible updates.
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
