on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: codeberg-tiny-lazy
    steps:
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none
      - run: echo "PATH=${HOME}/.cargo/bin:${PATH}" >> "${FORGEJO_ENV}"
      - run: rustup toolchain install stable --profile minimal --component clippy,rustfmt
      - uses: actions/checkout@v5
      - uses: cargo fmt
      - uses: cargo build --locked
      - uses: cargo clippy --locked
      - uses: cargo test --locked
