#!/bin/bash
# Copyright 2019–2020 Sebastian Wiesnser <sebastian@swsnr.de>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

next_version="$1"
if [[ -z "${next_version}" ]]; then
    echo "Next version missing; aborting"
    exit 1
fi

changes="$(git status --porcelain)"
if [[ -n "${changes}" ]]; then
    git status
    echo "Working directory not clean; aborting"
    exit 1
fi

if [[ "$(git symbolic-ref --short HEAD)" != "main" ]]; then
    echo "Not on main branch; aborting"
    exit 1
fi

latest_tag="$(git tag --sort '-v:refname' | grep '^v[0-9]' | head -n1)"
release_date="$(date +%Y-%m-%d)"

# Substitute version in Cargo.toml, force Cargo.lock update and add it to Git
sed -i'' "1,/^version =/ s/^version = .*$/version = \"$next_version\"/" Cargo.toml
cargo metadata --format-version 1 >/dev/null
git add Cargo.toml Cargo.lock

# Update revnumber and revdate and rebuild the manpage, then add it to Git
sed -i'' "1,/^:revnumber:/ s/^:revnumber: .*$/:revnumber: $next_version/" git-gone.1.adoc
sed -i'' "1,/^:revdate:/ s/^:revdate: .*$/:revdate: $release_date/" git-gone.1.adoc
asciidoctor -b manpage -a reproducible git-gone.1.adoc
MANWIDTH=80 man -l ./git-gone.1 > README
git add git-gone.1 git-gone.1.adoc README

# Update the changelog:
# 1. Append a headline for the current version right after [Unreleased] headline
# 2. Append link references for the new version and the new unreleased version
# 3. Delete the old link reference for the Unreleased header
sed -e "/^## \[Unreleased\]\$/ a\\
\\
## [${next_version}] – ${release_date}" \
    -e "\$a\\
[$next_version]: https://github.com/lunaryorn/git-gone/compare/v${latest_tag}...v${next_version}\\
[Unreleased]: https://github.com/lunaryorn/git-gone/compare/v${next_version}...HEAD" \
    -e '/^\[Unreleased\]:/ D' \
    -i'' CHANGELOG.md
git add CHANGELOG.md

git commit -m "Release $next_version"
cargo publish --no-verify
# Tag and push after successful publish
git tag -m "git-gone $next_version" "v$next_version"
git push --follow-tags origin main
